//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Speculator.SmartComData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartComData.ISmartComData")]
    public interface ISmartComData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartComData/DefaultOperation", ReplyAction="http://tempuri.org/ISmartComData/DefaultOperationResponse")]
        void DefaultOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartComData/DefaultOperation", ReplyAction="http://tempuri.org/ISmartComData/DefaultOperationResponse")]
        System.Threading.Tasks.Task DefaultOperationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartComDataChannel : Speculator.SmartComData.ISmartComData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartComDataClient : System.ServiceModel.ClientBase<Speculator.SmartComData.ISmartComData>, Speculator.SmartComData.ISmartComData {
        
        public SmartComDataClient() {
        }
        
        public SmartComDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartComDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartComDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartComDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DefaultOperation() {
            base.Channel.DefaultOperation();
        }
        
        public System.Threading.Tasks.Task DefaultOperationAsync() {
            return base.Channel.DefaultOperationAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartComData.IDataBase", CallbackContract=typeof(Speculator.SmartComData.IDataBaseCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDataBase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBase/ConnectToDataSource", ReplyAction="http://tempuri.org/IDataBase/ConnectToDataSourceResponse")]
        void ConnectToDataSource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBase/ConnectToDataSource", ReplyAction="http://tempuri.org/IDataBase/ConnectToDataSourceResponse")]
        System.Threading.Tasks.Task ConnectToDataSourceAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/ConnectToHistoryDataSource")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SpeculatorModel.SmartCom.SmartComSymbol))]
        void ConnectToHistoryDataSource(SpeculatorModel.MainData.Symbol symbol, System.DateTime dayDateTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/ConnectToHistoryDataSource")]
        System.Threading.Tasks.Task ConnectToHistoryDataSourceAsync(SpeculatorModel.MainData.Symbol symbol, System.DateTime dayDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBase/ListenSymbol", ReplyAction="http://tempuri.org/IDataBase/ListenSymbolResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SpeculatorModel.SmartCom.SmartComSymbol))]
        void ListenSymbol(SpeculatorModel.MainData.Symbol symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBase/ListenSymbol", ReplyAction="http://tempuri.org/IDataBase/ListenSymbolResponse")]
        System.Threading.Tasks.Task ListenSymbolAsync(SpeculatorModel.MainData.Symbol symbol);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/PlaceOrder")]
        void PlaceOrder(SpeculatorServices.Trading.TradingOrder order);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/PlaceOrder")]
        System.Threading.Tasks.Task PlaceOrderAsync(SpeculatorServices.Trading.TradingOrder order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataBaseCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/UpdateBidOrAskEvent")]
        void UpdateBidOrAskEvent(SpeculatorModel.SmartCom.SmartComSymbol symbol, SpeculatorModel.SmartCom.SmartComBidAskValue value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/TradeEvent")]
        void TradeEvent(SpeculatorModel.SmartCom.SmartComSymbol symbol, SpeculatorModel.SmartCom.SmartComTrade trade);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/QuoteEvent")]
        void QuoteEvent(SpeculatorModel.SmartCom.SmartComSymbol symbol, SpeculatorModel.SmartCom.SmartComQuote quote);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderSucceeded")]
        void OrderSucceeded(int cookie, string orderid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderFailed")]
        void OrderFailed(int cookie, string orderid, string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderMoveSucceeded")]
        void OrderMoveSucceeded(string orderid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderMoveFailed")]
        void OrderMoveFailed(string orderid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderCancelSucceeded")]
        void OrderCancelSucceeded(string orderid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/OrderCancelFailed")]
        void OrderCancelFailed(string orderid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/UpdatePosition")]
        void UpdatePosition(string portfolio, string symbol, double avprice, double amount, double planned);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/UpdateOrder")]
        void UpdateOrder(string portfolio, SpeculatorServices.Trading.TradingOrder order, double filled, System.DateTime datetime, string orderid, string orderno, int status_mask);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataBase/AddTrade")]
        void AddTrade(string portfolio, string symbol, string orderid, double price, double amount, System.DateTime datetime, string tradeno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataBaseChannel : Speculator.SmartComData.IDataBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBaseClient : System.ServiceModel.DuplexClientBase<Speculator.SmartComData.IDataBase>, Speculator.SmartComData.IDataBase {
        
        public DataBaseClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DataBaseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DataBaseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectToDataSource() {
            base.Channel.ConnectToDataSource();
        }
        
        public System.Threading.Tasks.Task ConnectToDataSourceAsync() {
            return base.Channel.ConnectToDataSourceAsync();
        }
        
        public void ConnectToHistoryDataSource(SpeculatorModel.MainData.Symbol symbol, System.DateTime dayDateTime) {
            base.Channel.ConnectToHistoryDataSource(symbol, dayDateTime);
        }
        
        public System.Threading.Tasks.Task ConnectToHistoryDataSourceAsync(SpeculatorModel.MainData.Symbol symbol, System.DateTime dayDateTime) {
            return base.Channel.ConnectToHistoryDataSourceAsync(symbol, dayDateTime);
        }
        
        public void ListenSymbol(SpeculatorModel.MainData.Symbol symbol) {
            base.Channel.ListenSymbol(symbol);
        }
        
        public System.Threading.Tasks.Task ListenSymbolAsync(SpeculatorModel.MainData.Symbol symbol) {
            return base.Channel.ListenSymbolAsync(symbol);
        }
        
        public void PlaceOrder(SpeculatorServices.Trading.TradingOrder order) {
            base.Channel.PlaceOrder(order);
        }
        
        public System.Threading.Tasks.Task PlaceOrderAsync(SpeculatorServices.Trading.TradingOrder order) {
            return base.Channel.PlaceOrderAsync(order);
        }
    }
}
